- name: Configure Klipper host prerequisites
  hosts: printers
  gather_facts: true
  roles:
    - base
    - security
    - klipper_config_repo
    - klipper
    - moonraker
    - crowsnest
    - webcam_https_proxy
    - moonraker_telegram_bot
    - klipper_tmc_autotune
    - shaketune
    - firewall
